### ISSUE TITLE
Lack of contribution guidelines

### ISSUE THREAD

**Issue by Jaideep-C** [c-code-x/codex-website#25]
### Lack of contribution guidelines
Clear and concise contribution guidelines should be made so that the contributors are comfortable understanding our organization's goals and guidelines
Please create these documents or markdowns to solve this issue

- [x] Contribution guidelines 
- [x] issue template
- [x] pull request template

Please refer these as an example [CONTRIBUTING.md ](https://gist.github.com/briandk/3d2e8b3ec8daf5a27a62) [ISSUE.md](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) [PR.md](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by the-amazing-atharva** [comment]
Hi!

I am a beginner here and would like to contribute to this project
I would like to make a CONTRIBUTING.md file and then later try adding the templates

**Comment by Jaideep-C** [comment]
@the-amazing-atharva sure. You are assigned for this issue, please don't hesitate to reach out for any help in this thread

**Comment by the-amazing-atharva** [comment]
would this work?

![image](https://user-images.githubusercontent.com/121221252/218315900-ac87777c-2e1b-4a6b-a03f-c6426028f5e0.png)

**Comment by Jaideep-C** [comment]
Yep! it looks great waiting for the PR

**Comment by the-amazing-atharva** [comment]
Sending it soon
