### ISSUE TITLE
Ambiguous homepage or landing page

### ISSUE THREAD

**Issue by Jaideep-C** [c-code-x/codex-website#26]
### Ambiguous homepage or landing page
Currently, we have two different pages with the same content. That is the landing page and the root index page.
Those two pages are

1. `pages/index.tsx`
2. `pages/LandingPage.tsx`

When a user visits our webpage, they are served `pages/index.tsx` as the home page, but when they go to an under construction page and try to navigate via the button "go back", they are redirected to `pages/LandingPage.tsx` as the homepage in which the title of the page is also broken and not updated.

### Possible solution
I think `pages/index.tsx` is supposed to be the home page and `pages/LandingPage.tsx` is just a refactored component which contains the content of the home page. A possible solution would be to refactor the `pages/LandingPage.tsx` to `components/LandingPage.tsx` this way we can treat it as a component rather than a page.

Also we need to change the hyperlink `<Link href={"/"}><button>Go Back</button></Link>`

**Comment by punith-dandluri** [comment]
hi
I want to resolve issue.
Process:
- Delete the landing page.
- make the index.tsx as landing page
- update all the links referred.

**Comment by Jaideep-C** [comment]
this issue is fixed in #38 PR
