### ISSUE TITLE
Defective Navbar

### ISSUE THREAD

**Issue by punith-dandluri** [c-code-x/codex-website#52]
#Defective Navigation bar
Currently, we have navigation bar component, the issue is, when on small screens like mobile phones, if the page is reloaded, suddenly NAVIGATION bar appears or goes.

##Possibly
1. `Change the logic of NAVIGATION BAR`
2. `Check with the State Functionality of the logic`

## Guidelines to Issue Contributor
1. `Make your changes, send PR only to alpha branch`
2. `Follow Contributors.md to achieve the acceptance of PR `

**Comment by CodeX-GITAM** [comment]
This issue is solved in the #80.
